# Generated by Django 2.2 on 2020-10-23 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cyberpank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('desc', models.TextField(blank=True)),
                ('release', models.CharField(max_length=128)),
                ('country', models.CharField(max_length=128)),
                ('director', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Киберпанк',
                'verbose_name_plural': 'Киберпанк',
            },
        ),
        migrations.CreateModel(
            name='fantasy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('desc', models.TextField(blank=True)),
                ('release', models.CharField(max_length=128)),
                ('country', models.CharField(max_length=128)),
                ('director', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Фэнтези',
                'verbose_name_plural': 'Фэнтези',
            },
        ),
        migrations.CreateModel(
            name='shounen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('desc', models.TextField(blank=True)),
                ('release', models.CharField(max_length=128)),
                ('country', models.CharField(max_length=128)),
                ('director', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Сёнэн',
                'verbose_name_plural': 'Сёнэн',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категорию', 'verbose_name_plural': 'Категории'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='category',
        ),
        migrations.RemoveField(
            model_name='category',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='category',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='SubjectCategory',
        ),
        migrations.AddField(
            model_name='shounen',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Category'),
        ),
        migrations.AddField(
            model_name='fantasy',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Category'),
        ),
        migrations.AddField(
            model_name='cyberpank',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Category'),
        ),
    ]
