# Generated by Django 2.2 on 2020-12-17 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='address',
            new_name='author',
        ),
    ]
